# Generated by Django 4.0.3 on 2022-04-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articale_list',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
